version: 2
updates:
  - package-ecosystem: docker
    directories:
      - '/'
      - '/apps/*/'
      - '/libs/*/'
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directories:
      - '/'
      - '/apps/*/'
      - '/libs/*/'
    schedule:
      interval: monthly
