name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - uses: nrwl/nx-set-shas@v4

      - run: >
          pnpm dlx nx-cloud start-ci-run \
          --distribute-on .nx/workflows/dynamic-changesets.yaml \
          --stop-agents-after build

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm exec nx affected -t lint test build --parallel $(nproc)
