name: CI

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_CLOUD_ENCRYPTION_KEY: ${{ secrets.NX_CLOUD_ENCRYPTION_KEY }}

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4.0.0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version-file: package.json
          cache: pnpm

      - uses: nrwl/nx-set-shas@v4.1.1

      - run: >
          pnpm dlx nx-cloud start-ci-run \
          --distribute-on .nx/workflows/dynamic-changesets.yaml \
          --stop-agents-after e2e-ci

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm exec nx affected -t lint build --parallel=$(nproc)
      - run: pnpm exec nx affected -t test e2e-ci --parallel=$(nproc) -- --runInBand
